### ISSUE TITLE
readme should specify minimum working versions

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/cluster-api-provider-kubemark#13]
the readme currently instructs the user to install the 0.2.2 release of the kubemark provider but does not mention which version of cluster-api should be used. we should ensure that where the docs call out a specific version of the kubemark provider, that we also indicate a version of cluster-api to use. this will help reduce user frustrations when attempting to get the kubemark provider working properly.

**Comment by elmiko** [comment]
it might be nice to have a compatibility chart like the aws provider, see https://github.com/kubernetes-sigs/cluster-api-provider-aws#compatibility-with-cluster-api-and-kubernetes-versions

/remove-lifecycle stale

**Comment by agradouski** [comment]
/remove-lifecycle stale
this is related to https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/issues/10
will update the docs once it's implemented (PR has been submitted internally, will create upstream PR shortly)

**Comment by agradouski** [comment]
/close
this was fixed with PR https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/pull/43
