### ISSUE TITLE
Allow to specify external cluster for hollow pods

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-kubemark#20]
When using kubermak I would like to have a knob to deploy hollow pods on an external cluster, because if I would like to avoid any noise on the management cluster where I'm monitoring performances of CAP components 

A prior art for this was implemented in https://github.com/kubernetes-sigs/cluster-api/pull/4566

**Comment by luwang-vmware** [comment]
Have a same request. +1.

**Comment by elmiko** [comment]
just for clarity, this would be bringing the `ExternalCluster` field and logic into the `KubemarkMachine` resource?

**Comment by fabriziopandini** [comment]
Yes, that's the simplest solution IMO

**Comment by gabhi** [comment]
actively working on this
