### ISSUE TITLE
Basic CI implementation

### ISSUE THREAD

**Issue by agradouski** [kubernetes-sigs/cluster-api-provider-kubemark#26]
We need to implement a rudimentary CI for the project.

As a first iteration we can implement and check in a common test script to be used for manual validation of any code changes by developers.

As a follow-up we can hook it up with prow/test-infra, to execute validation pipeline(s) automatically for all PRs.

**Comment by elmiko** [comment]
i think this sounds solid. i think it would also be worthwhile to investigate adding the kubebuilder envtest scaffolding to the code base. imo, we could have some room for unit testing at the very least in the future.

**Comment by agradouski** [comment]
/remove-lifecycle stale
a PR for this has been pending internally for a while, should create upstream PR soon

**Comment by elmiko** [comment]
awesome to hear, thanks for the update @agradouski
