### ISSUE TITLE
should the default registry locations be changed?

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/cluster-api-provider-kubemark#3]
the [current default image locations](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/master/Makefile#L46-L47) are prefixed to `gcr.io/cf-london-servces-k8s/bmo/`, which might be @benmoss' personal account space. should this be moved to a location where other kubernetes-sigs/cluster-api related content lives? does such a place exist?

[looks like](https://github.com/kubernetes-sigs/cluster-api/blob/master/Makefile#L79) some of the main cluster-api project images are at `gcr.io/k8s-staging-cluster-api`, that may be an option.

**Comment by benmoss** [comment]
Yeah, probably! 😄

**Comment by elmiko** [comment]
hi Ben! i'm going to bring this up at the cluster-api meeting this week, hopefully we can just use the staging.

**Comment by CecileRobertMichon** [comment]
Not sure how much work that would be to set it up but we could have a separate staging registry for kubemark, like we do for other providers eg. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Makefile#L102

**Comment by elmiko** [comment]
i am making some images available in my personal quay.io account at quay.io/elmiko/kubemark. i would like to propose using these images until we can find a better place. ultimately it would be beneficial to automate this process, but it requires building the various kubemark versions into images and i'm not sure where the proper place for this would be.

**Comment by gabhi** [comment]
@elmiko looks like currently ```cr.io/cf-london-servces-k8s/bmo/cluster-api-kubemark/cluster-api-kubemark-controller:v0.2.2``` is not present so because of which I m getting the following error

```
capk-system                         capk-controller-manager-77765c9d7d-dhjj4                         1/2     ImagePullBackOff   1          24h

```

will you be able to host this image in your namespace?

**Comment by elmiko** [comment]
hey @gabhi , yes i have started to create images in my personal repo https://quay.io/repository/elmiko/kubemark?tag=latest&tab=tags

if everyone is ok with this, i can post a change to update the default location. it would be nice to ultimately find a home for the these images in a more "official" location, but currently the automation to build them all is slightly bespoke.

**Comment by gabhi** [comment]
@elmiko do you who can help us in creating staging area? how should we proceed about this?

**Comment by luwang-vmware** [comment]
@elmiko May I know how I can use the code of https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/main.go#L56 to create mgmt cluster? Currently, it is stucked in "Back-off pulling image "gcr.io/cf-london-servces-k8s/bmo/cluster-api-kubemark/cluster-api-kubemark-controller:dev".

**Comment by luwang-vmware** [comment]
Thanks @elmiko for the detail info. I mixed kubemark image and kubemark-controller image before.  I use the dockerfile in this repo to build my own kubemark-controller image and live edit the capk-controller-manager  deployment to use the one I build. Now capk-controller-manager is running now.

**Comment by elmiko** [comment]
i think we have answered this question, i am going to close this issue and create a new issue to capture the work. thanks everyone!

**Comment by elmiko** [comment]
created #37
