### ISSUE TITLE
Consider if to align manager flag names with upstream Kubernetes components

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-kubemark#31]
While working on [adding support for Prometheus in CAPI TiltFile](https://github.com/kubernetes-sigs/cluster-api/pull/6117) we noticed that latest CAPK is still using old flags name for metrics and leader election (see 
https://cluster-api.sigs.k8s.io/developer/providers/v0.3-to-v0.4.html#align-manager-flag-names-with-upstream-kubernetes-components).

Even this is not mandatory, I suggest the CAPK team consider aligning flag names for sake of consistency across providers; also deploying Prometheus in local dev env using the CAPI Tiltfile won't work without this change as well as "--metrics-bind-addr=127.0.0.1:8080" in your `manager.yaml` file suggested in the same doc linked above.

**Comment by elmiko** [comment]
thanks for bringing this up @fabriziopandini !

**Comment by elmiko** [comment]
for anyone curious about fixing this, these lines will need to be changed (as per the advice linked above), https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/main.go#L55-L58

also, as Fabrizio mentioned, the manifest for the manager deployment will need to changed as well, see https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/config/manager/manager.yaml

**Comment by deepakmega** [comment]
hi @elmiko ,
I have also found references of older name "--metrics-addr"  and "--enable-leader-election" in the below files

- https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/config/manager/manager_auth_proxy_patch.yaml#L24-L25
- https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/config/default/manager_auth_proxy_patch.yaml#L24-L25

Let me know if the above files also needs to be changed. Ill create a PR once verified..

Changes :
- Renaming  --metrics-addr to --metrics-bind-addr
- Renaming  --enable-leader-election to --leader-elect

**Comment by elmiko** [comment]
good investigation @deepakmega !

those flags are for the kube-rbac-proxy that is deployed in the cluster, i think we should leave them alone for now and just fix the flag names for the kubemark provider. my reasoning for this is that we have version `v0.4.1` in that manifest, and it looks like upstream is at `v0.11.0` (https://github.com/brancz/kube-rbac-proxy/releases).

so, i think it would be nice to upgrade that image to the latest version, and also update the flags. but i think we should do it on another pull request. if you would like to investigate and test fixing that as well, i think it would be awesome =)

**Comment by deepakmega** [comment]
Sorry for creating multiple PR's , had issue with EasyCla. 
Have created a PR #35 to fix the same.
@elmiko  I will create another PR for updating the image to latest version along with updated flags and test the same.
