### ISSUE TITLE
Run Cluster API stress tests using kubemark

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-kubemark#63]
**User Story**

As a Cluster API maintainer, I would like to use Kubemark for running Cluster API stress test

**Detailed Description**

As of today, Kubemark can be used for creating lightweight worker nodes, but it still depends on CAPD or other providers using "real infrastructure" for the control plane nodes.

This is a limitation when I try to use Kubemark for running Cluster API stress test, where the number of clusters being managed is a key parameter (as well as the number of machines).

What I'm proposing here is to introduce support for a "KubermarkControlPlane" CRD, which will run a lightweight CP using pods, and a corresponding "KubemarkCluster" CRD providing a load balancer in front of it using Kubernetes services or eventually an ingress.

The goal, is to run CAPI stress tests using a single VM to run the management cluster + prometheus or something to collect metrics about how the system is performing, while using GKE or some other managed Kubernetes service as a backing cluster for running pods for both CP components and kubemark

**Anything else you would like to add:**

The implementation requires 3 main tasks:
- Refactor [the current KubemarkCluster](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/controllers/kubemarkcluster.go) into a backing cluster; this is required for two reasons:
   - To disambiguate from the KubemarkCluster" CRD that will be introduced in the following steps
   - To ensure this component does not become a bottleneck at scale (it currently creates a client at each reconciliation, and we already saw in Cluster API that this is a problem; it must be refactored by implementing something similar to the cluster tracker in CAPI)
 - Introduce "KubermarkControlPlane" and "KubemarkCluster" CRDs and corresponding controllers
 - Wire up everything ensuring it works with cluster class + there is an E2E test for it
 
A prototype of this work can be found in https://github.com/fabriziopandini/cluster-api-provider-kubemark/tree/kubemark-controlplane

cc @elmiko @killianmuldoon 

/kind feature

**Comment by elmiko** [comment]
i think this sounds really cool and ambitious, thanks for bringing the issue @fabriziopandini

**Comment by fabriziopandini** [comment]
These are notes about great work on CAPI scale testing from @lentzi90 
https://github.com/Nordix/metal3-clusterapi-docs/tree/lentzi90/scaling-experiments-v2/metal3-scaling-experiments

**Comment by elmiko** [comment]
i think this is still relevant and i am curious to see it move forward.

/remove-lifecycle stale

**Comment by elmiko** [comment]
i still want to see this happen

/reopen
